### Sign In user
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email": "foo1@foo.com",
    "password": "test"
}

### Create a report
POST http://localhost:3000/reports
content-type: application/json

{
  "make": "Ford",
  "model": "Mustang",
  "year": 2017,
  "price": 20000,
  "mileage": 10000,
  "lat": 37.7749,
  "lng": -122.4194
}

### Approve a report
PATCH http://localhost:3000/reports/4
content-type: application/json

{
  "approved": true
}

### Get an estimate for an existing vehicle
GET http://localhost:3000/reports?make=Ford&model=Mustang&year=2016&mileage=15000&lat=37.7749&lng=-122.4194

